services:

  wiremock:
    image: wiremock/wiremock:latest
    container_name: wiremock
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/certs/keystore.p12:/home/wiremock/keystore.p12
    command: >
      --port 8080
      --https-port 8443
      --https-keystore /home/wiremock/keystore.p12
      --keystore-password password
      --keystore-type PKCS12
      --verbose
